#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Explorations!?  # The title of the book. Will be placed in the left navbar.
author                      : Erik J Peterson  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Don't execute.
execute:
  execute_notebooks         : off

# Information about where the book exists on the web
repository:
  url                       : https://github.com/parenthetical-e/explorations-book
  path_to_book              : book/
  branch                    : main 

# only_build_toc_files        : true
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org" 